[versions]
activityCompose = "1.11.0"
agp = "8.13.0"
applovin = "13.5.0.0"
appUpdateKtx = "2.1.0"
billingKtx = "8.0.0"
browser = "1.9.0"
commonsIo = "2.20.0"
composeBomVersion = "2025.10.01"
constraintlayoutCompose = "1.1.1"
converterGson = "3.0.0"
dexter = "6.2.3"
emoji2Emojipicker = "1.6.0"
glide = "5.0.5"
groupie = "2.10.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesCore = "1.10.2"
library = "2.2.0"
lifecycleCompiler = "2.9.4"
lifecycleLivedataKtx = "2.9.4"
lifecycleProcess = "2.9.4"
lifecycleViewmodelKtx = "2.9.4"
lottie = "6.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"

gms = "4.4.4"
crashlytics = "3.0.6"
mintegral = "16.10.11.0"
navigation = "2.9.5"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
okhttp = "5.3.0"
pangle = "7.7.0.2.0"
perf = "2.0.2"

firebaseBom = "34.5.0"
firebaseCore = "21.1.1"
firebaseCrashlytics = "20.0.3"
firebaseMessaging = "25.0.1"
firebasePerf = "22.0.3"
playServicesAds = "24.7.0"
preferenceKtx = "1.2.1"
retrofit = "3.0.0"
roomRuntime = "2.8.3"
runtimeLivedata = "1.9.4"
sdpAndroid = "1.1.1"
shimmer = "0.5.0"
sot_fof_andadslib = "3.1.3"
sspAndroid = "1.1.1"
userMessagingPlatform = "4.0.0"
ztZip = "1.17"
colorpicker = "0.0.15"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-emoji2-emojipicker = { module = "androidx.emoji2:emoji2-emojipicker", version.ref = "emoji2Emojipicker" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycleCompiler" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
applovin = { module = "com.google.ads.mediation:applovin", version.ref = "applovin" }
#billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
groupie = { module = "com.github.lisawray.groupie:groupie", version.ref = "groupie" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
library = { module = "com.anjlab.android.iab.v3:library", version.ref = "library" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebasePerf" }
mintegral = { module = "com.google.ads.mediation:mintegral", version.ref = "mintegral" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
pangle = { module = "com.google.ads.mediation:pangle", version.ref = "pangle" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
sot_fof_andadslib = { module = "com.github.Kalimullah95:SOT_FOF_AndAdsLib", version.ref = "sot_fof_andadslib" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
user-messaging-platform = { module = "com.google.android.ump:user-messaging-platform", version.ref = "userMessagingPlatform" }
zt-zip = { module = "org.zeroturnaround:zt-zip", version.ref = "ztZip" }
colorpicker = { module = "com.github.QuadFlask:colorpicker", version.ref = "colorpicker" }

[plugins]


com-google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
com-google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
com-google-firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "perf" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }